import Head from 'next/head'
import { Layout, Section, Typography } from '../components'

export default function Contact() {
  return (
    <div>
      <Head>
        <title>Tomateto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Section>
          <div>
            <Typography size="h2" weight="black" color="secondary">Contact</Typography>
          </div>
          <div></div>
        </Section>
      </Layout>
    </div>
  )
}
