import Head from 'next/head'
import { ContactForm, Container, Layout, Section, Typography, LinkTypography } from '../components'

export default function Contact() {
  return (
    <div>
      <Head>
        <title>Contact | Adam Darmawan | Software Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Section>
          <div>
            <Container padding="180px 0" alignItems="center" mdDown="padding: 120px 30px;">
                <Container maxWidth="600px" spacing={60}>
                    <Container>
                        <Typography size="h2" weight="black" color="secondary" mdDown="font-size: 48px">Contact me</Typography>
                    </Container>
                    <Container spacing={60}>
                        <Typography weight="medium">
                          Hey, it&apos;s nice to see you here. Feel free to use the form below to get in touch, whether you got an opportunity to talk about, something you&apos;d like to ask, or just want to talk about the latest movies. Looking forward to hearing from you!
                          <br /><br />
                          Alternatively, my inbox is always open at <LinkTypography href="mailto:adam@adamscript.com">adam@adamscript.com</LinkTypography>.
                          <br /><br />
                          You can also find me on <LinkTypography href="https://www.linkedin.com/in/adamscript">LinkedIn</LinkTypography>.
                        </Typography>
                        <ContactForm />
                    </Container>
                </Container>
            </Container>
          </div>
          <div></div>
        </Section>
      </Layout>
    </div>
  )
}
