import Head from 'next/head'
import Vercel from '../public/vercel.svg'
import Tomateto from '../public/icons/logos/tomatetodark-icon.svg'

import { Button, Chip, Icon, Layout, Section, Typography } from '../components';

export default function Home() {

  const handleClick = () => {
    console.log('clicked');
  }

  return (
    <div>
      <Head>
        <title>Tomateto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Section>
          <div>
            <Typography size="h6" color="secondary">Hello World h6</Typography>
            <Typography size="h5" weight="bold">Hello World h5</Typography>
            <Typography size="h2" weight="black">Hello World h2</Typography>
            <Typography size="caption" weight="light" slab>hello world caption text</Typography>
            <Button width="98px">Click me</Button>
            <Button width="98px" outlined>Button</Button>
            <Typography>Hello World body</Typography>
            <Icon label="Technology" size={4}>
              <Vercel />
            </Icon>
            <Icon label="Technology" onClick={handleClick} hideLabel size={2}>
              <Vercel />
            </Icon>
            <Icon label="Tomateto" onClick={handleClick} hideLabel size={2}>
              <Tomateto />
            </Icon>
            <Chip>React</Chip>
            <Chip>Styled Components</Chip>
          </div>
          <div></div>
        </Section>
      </Layout>
    </div>
  )
}
